version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7

    commands:
      - echo install

  pre_build:
    commands:
      - echo prebuild

  build:
    commands:
      - echo build

  post_build:
    commands:
      - echo post_build